name: Node Test

on:
  push:
    branches-ignore:
      - 'master'  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: zemuldo/git-crypt-unlock
      uses: zemuldo/git-crypt-unlock@v2.0
      env: 
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
        GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}

    - name: npm install, build, and test
      env:
        CI: true
        UI_URL: ${{ secrets.UI_URL }}
        PORT: ${{ secrets.PORT }}
        UI_URL_DOMAIN: ${{ secrets.UI_URL_DOMAIN }}
        API_URL: ${{ secrets.API_URL }}
        GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
      run: |
        npm install
        ./setup/version_info.sh
        npm test  -- --u
