name: Build & Publish
on: 
  push:
      branches:    
          - master
jobs:
  # to_gcr_io:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1

  #   - name: Git-Crypt Unlock
  #     uses: zemuldo/git-crypt-unlock@master
  #     env: 
  #       GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  #       GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
  #       GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}

  #   - name: Setup Release Details
  #     run: |
  #         touch .env.production
  #         echo API_URL=${{ secrets.PROD_API_URL }} >> .env.production
  #         echo UI_URL=${{ secrets.PROD_UI_URL }} >> .env.production
  #         echo UI_URL_DOMAIN=${{ secrets.PROD_UI_URL_DOMAIN }} >> .env.production
  #         echo GA_TRACKING_ID=${{ secrets.PROD_GA_TRACKING_ID }} >> .env.production
  #         echo "GITHUB_SHA=${GITHUB_SHA}" >> .env.production
  #         echo "BRANCH=${GITHUB_REF##*/}" >> .env.production
  #         echo VERSION=`jq '.version' package.json` >> .env.production

  #   - name: Build and Push
  #     uses: zemuldo/docker-build-push@master
  #     env:
  #       GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
  #       GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  #       GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
  #       REGISTRY_URL: "gcr.io"
  #     with:
  #      image_name: "site-ui"
  #      image_tag: "latest"

  to_docker_io:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Git-Crypt Unlock
      uses: zemuldo/git-crypt-unlock@master
      env: 
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
        GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}

    - name: Setup Release Details
      run: |
          touch .env.production
          echo API_URL=${{ secrets.PROD_API_URL }} >> .env.production
          echo UI_URL=${{ secrets.PROD_UI_URL }} >> .env.production
          echo SITE_IMAGES_URL=${{ secrets.SITE_IMAGES_URL }} >> .env.production
          echo UI_URL_DOMAIN=${{ secrets.PROD_UI_URL_DOMAIN }} >> .env.production
          echo GA_TRACKING_ID=${{ secrets.PROD_GA_TRACKING_ID }} >> .env.production
          echo "GITHUB_SHA=${GITHUB_SHA}" >> .env.production
          echo "BRANCH=${GITHUB_REF##*/}" >> .env.production
          echo VERSION=`jq '.version' package.json` >> .env.production

    - name: Build and Push
      uses: zemuldo/docker-build-push@master
      env:
        DOCKER_USERNAME: "zemuldo"
        DOCKER_NAMESPACE: "zemuldo"
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        REGISTRY_URL: "docker.io"
      with:
       image_name: "site-ui"
       image_tag: "latest"
    

    